package com.example.open_fantasia.domain.model

import kotlinx.serialization.Serializable

/**
 * A supporting / side character present in a thread alongside the main character. The narrator
 * (the main character's reply) voices these NPCs; their identity cards live in the cached system
 * prefix, while their volatile state is tracked in durable_state on the suffix.
 *
 * IMPORTANT: deliberately NOT @Serializable, and the persisted JSON lives only on the Room
 * ThreadEntity (column `supporting_cast`), never on the @Serializable ThreadRecord. A
 * @Serializable CastMember combined with reified serializer extensions tripped a K2-kapt +
 * kotlinx.serialization compiler crash ("IrConstructorSymbolImpl is already bound"). It is
 * encoded/decoded via the runtime JSON element API in [parseSupportingCast]/[toSupportingCastJson].
 */
data class CastMember(
    val name: String = "",
    val description: String = ""
)

@Serializable
data class ProfileRecord(
    val id: String,
    val username: String,
    val created_at: String,
    val updated_at: String
)

@Serializable
data class ModelCatalogEntry(
    val id: String,
    val name: String,
    val provider: String, // "google" | "groq" | "mistral" | "openrouter" | "ollama" | "deepseek"
    val contextWindow: Int? = null,
    val hint: String? = null,
    val supportsJson: Boolean = false // verified JSON-mode capable (strict: only true from a discovery signal)
)

@Serializable
data class ConnectionRecord(
    val id: String,
    val user_id: String,
    val provider: String,
    val label: String,
    val base_url: String?,
    val encrypted_api_key: String?,
    val enabled: Boolean,
    val default_model_id: String?,
    val model_cache: List<ModelCatalogEntry>,
    val health_status: String, // "untested" | "healthy" | "auth_failed" ...
    val health_message: String,
    val last_checked_at: String?,
    val last_model_refresh_at: String?,
    val last_synced_at: String?,
    val created_at: String,
    val updated_at: String
)

@Serializable
data class UserPersonaRecord(
    val id: String,
    val user_id: String,
    val name: String,
    val identity: String = "",
    val backstory: String = "",
    val voice_style: String = "",
    val goals: String = "",
    val boundaries: String = "",
    val private_notes: String = "",
    val is_default: Boolean = false,
    val created_at: String,
    val updated_at: String
)

@Serializable
data class ExampleConversation(
    val user_line: String,
    val character_line: String
)

@Serializable
data class CharacterRecord(
    val id: String,
    val user_id: String,
    val name: String,
    val story: String = "",
    val core_persona: String = "",
    val greeting: String = "",
    val appearance: String = "",
    val style_rules: String = "",
    val definition: String = "",
    val negative_guidance: String = "",
    val temperature: Double = 0.92,
    val top_p: Double = 0.94,
    val starters: List<String> = emptyList(),
    val example_conversations: List<ExampleConversation> = emptyList(),
    val portrait_status: String = "idle", // "idle" | "pending" | "ready" | "failed"
    val portrait_path: String? = null,
    val portrait_prompt: String? = null,
    val portrait_seed: Int? = null,
    val portrait_source_hash: String? = null,
    val portrait_last_error: String? = null,
    val portrait_generated_at: String? = null,
    val created_at: String,
    val updated_at: String
)

@Serializable
data class CharacterBundle(
    val character: CharacterRecord,
    val starters: List<String>,
    val exampleConversations: List<ExampleConversation>
)

@Serializable
data class ThreadRecord(
    val id: String,
    val user_id: String,
    val character_id: String,
    val connection_id: String,
    val model_id: String,
    val persona_id: String?,
    val brain_connection_id: String?,
    val brain_model_id: String?,
    val reply_length: String = "full",
    val director_notes: String = "",
    val title: String,
    val is_title_autogenerated: Boolean = true,
    val status: String = "active", // "active" | "archived"
    val archived_at: String? = null,
    val pinned_at: String? = null,
    val created_at: String,
    val updated_at: String
)

@Serializable
data class ChatBranchRecord(
    val id: String,
    val thread_id: String,
    val name: String,
    val parent_branch_id: String?,
    val fork_turn_id: String?,
    val head_turn_id: String?,
    val is_active: Boolean,
    val generation_locked: Boolean = false,
    val locked_by_turn_id: String? = null,
    val locked_at: String? = null,
    val created_by: String,
    val created_at: String,
    val updated_at: String
)

@Serializable
data class ChatTurnRecord(
    val id: String,
    val thread_id: String,
    val branch_origin_id: String,
    val parent_turn_id: String?,
    val user_input_text: String,
    val user_input_payload: String, // Stringified JSON array of parts
    val user_input_hidden: Boolean = false,
    val starter_seed: Boolean = false,
    val assistant_output_text: String?,
    val assistant_output_payload: String?,
    val generation_status: String, // "reserved" | "streaming" | "committed" | "failed"
    val reserved_by_user_id: String,
    val assistant_provider: String? = null,
    val assistant_model: String? = null,
    val assistant_connection_label: String? = null,
    val finish_reason: String? = null,
    val total_tokens: Int? = null,
    val prompt_tokens: Int? = null,
    val completion_tokens: Int? = null,
    val feedback_rating: Int? = null,
    val generation_started_at: String,
    val generation_finished_at: String? = null,
    val failure_code: String? = null,
    val failure_message: String? = null,
    val created_at: String,
    val updated_at: String
)

@Serializable
data class TimelineEventRecord(
    val id: String,
    val thread_id: String,
    val branch_id: String,
    val turn_id: String?,
    val title: String,
    val detail: String,
    val importance: Int, // 1-5
    val event_type: String, // "beat" | "reveal" | "betrayal" ...
    val affected_entity_ids: List<String> = emptyList(),
    val affected_relationship_ids: List<String> = emptyList(),
    val created_at: String
)

@Serializable
data class ChatPinRecord(
    val id: String,
    val thread_id: String,
    val branch_id: String,
    val turn_id: String?,
    val body: String,
    val status: String = "active", // "active" | "resolved"
    val created_at: String,
    val updated_at: String
)

@Serializable
data class CharacterPortraitTaskRecord(
    val id: String,
    val character_id: String,
    val user_id: String,
    val prompt: String,
    val seed: Long,
    val source_hash: String,
    val status: String, // "pending" | "running" | "succeeded" | "failed"
    val attempts: Int = 0,
    val max_attempts: Int = 8,
    val available_at: String,
    val locked_at: String? = null,
    val last_error: String? = null,
    val created_at: String,
    val updated_at: String
)
