package com.example.open_fantasia.ui.dashboard

import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.room.Room
import androidx.test.platform.app.InstrumentationRegistry
import com.example.open_fantasia.data.local.db.OpenFantasiaDatabase
import com.example.open_fantasia.data.local.entity.CharacterEntity
import com.example.open_fantasia.data.local.entity.ConnectionEntity
import com.example.open_fantasia.data.local.entity.ProfileEntity
import com.example.open_fantasia.data.local.entity.ThreadEntity
import org.junit.After
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import java.io.IOException
import kotlinx.coroutines.runBlocking

class DashboardScreenTest {

    @get:Rule
    val composeTestRule = createComposeRule()

    private lateinit var db: OpenFantasiaDatabase
    private lateinit var viewModel: DashboardViewModel

    @Before
    fun createDb() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        db = Room.inMemoryDatabaseBuilder(context, OpenFantasiaDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        viewModel = DashboardViewModel(db.chatDao(), db.characterDao(), db.connectionDao(), db.personaDao())
    }

    @After
    @Throws(IOException::class)
    fun closeDb() {
        db.close()
    }

    @Test
    fun dashboardScreen_showsEmptyState_whenNoThreads() {
        composeTestRule.setContent {
            DashboardScreen(viewModel = viewModel, onThreadSelected = {}, onNavigateToTab = {})
        }
        composeTestRule.onNodeWithText("No threads found.").assertExists()
    }

    @Test
    fun dashboardScreen_showsActiveThreadsList() {
        val fixedUserId = "00000000-0000-0000-0000-000000000000"
        val now = java.time.Instant.now().toString()

        val char = CharacterEntity(
            id = "char-1",
            user_id = fixedUserId,
            name = "Vex Halcyon",
            story = "Neon Syndicate",
            core_persona = "Glitch",
            greeting = "Ready",
            appearance = "", style_rules = "", definition = "", negative_guidance = "",
            temperature = 0.7, top_p = 0.9, starters = emptyList(), example_conversations = emptyList(),
            portrait_status = "none", portrait_path = null, portrait_prompt = null,
            portrait_seed = null, portrait_source_hash = null, portrait_last_error = null,
            portrait_generated_at = null, created_at = now, updated_at = now
        )
        val thread = ThreadEntity(
            id = "thread-1",
            user_id = fixedUserId,
            character_id = "char-1",
            connection_id = "conn-1",
            model_id = "gemini-1.5-flash",
            persona_id = null,
            brain_connection_id = null,
            brain_model_id = null,
            max_output_tokens = 4096,
            title = "The Neon Syndicate Infiltration",
            is_title_autogenerated = false,
            status = "active",
            archived_at = null,
            pinned_at = null,
            created_at = now,
            updated_at = now
        )
        val connection = ConnectionEntity(
            id = "conn-1",
            user_id = fixedUserId,
            provider = "google",
            label = "Google AI",
            base_url = null,
            encrypted_api_key = null,
            enabled = true,
            default_model_id = "gemini-1.5-flash",
            model_cache = emptyList(),
            health_status = "healthy",
            health_message = "",
            last_checked_at = null,
            last_model_refresh_at = null,
            last_synced_at = null,
            created_at = now,
            updated_at = now
        )
        runBlocking {
            db.profileDao().insertProfile(ProfileEntity(fixedUserId, "LocalUser", now, now))
            db.connectionDao().insertConnection(connection)
            db.characterDao().insertCharacter(char)
            db.chatDao().insertThread(thread)
        }

        composeTestRule.setContent {
            DashboardScreen(viewModel = viewModel, onThreadSelected = {}, onNavigateToTab = {})
        }

        // Verify thread title displays
        composeTestRule.onNodeWithText("The Neon Syndicate Infiltration").assertExists()
        // Verify character name displays under it
        composeTestRule.onNodeWithText("Vex Halcyon").assertExists()
    }

    @Test
    fun dashboardScreen_showsReadinessChecklist_whenOnboardingIncomplete() {
        // Since no connections or personas are inserted, onboarding should be incomplete.
        composeTestRule.setContent {
            DashboardScreen(viewModel = viewModel, onThreadSelected = {}, onNavigateToTab = {})
        }

        // Verify onboarding card header exists
        composeTestRule.onNodeWithText("Workspace Readiness").assertExists()
        // Verify incomplete step exists
        composeTestRule.onNodeWithText("Create a Persona").assertExists()
    }

    @Test
    fun dashboardScreen_filtersThreadsBySearchQuery() {
        val fixedUserId = "00000000-0000-0000-0000-000000000000"
        val now = java.time.Instant.now().toString()

        val char = CharacterEntity(
            id = "char-1", user_id = fixedUserId, name = "Vex", story = "", core_persona = "", greeting = "",
            appearance = "", style_rules = "", definition = "", negative_guidance = "",
            temperature = 0.7, top_p = 0.9, starters = emptyList(), example_conversations = emptyList(),
            portrait_status = "none", portrait_path = null, portrait_prompt = null,
            portrait_seed = null, portrait_source_hash = null, portrait_last_error = null,
            portrait_generated_at = null, created_at = now, updated_at = now
        )
        val thread1 = ThreadEntity(
            id = "thread-1", user_id = fixedUserId, character_id = "char-1", connection_id = "conn-1",
            model_id = "gemini-1.5-flash", persona_id = null, brain_connection_id = null, brain_model_id = null,
            max_output_tokens = 4096, title = "Match This Title", is_title_autogenerated = false,
            status = "active", archived_at = null, pinned_at = null, created_at = now, updated_at = now
        )
        val thread2 = ThreadEntity(
            id = "thread-2", user_id = fixedUserId, character_id = "char-1", connection_id = "conn-1",
            model_id = "gemini-1.5-flash", persona_id = null, brain_connection_id = null, brain_model_id = null,
            max_output_tokens = 4096, title = "Ignore This One", is_title_autogenerated = false,
            status = "active", archived_at = null, pinned_at = null, created_at = now, updated_at = now
        )

        runBlocking {
            db.profileDao().insertProfile(ProfileEntity(fixedUserId, "LocalUser", now, now))
            db.connectionDao().insertConnection(testConnection(fixedUserId, now))
            db.characterDao().insertCharacter(char)
            db.chatDao().insertThread(thread1)
            db.chatDao().insertThread(thread2)
        }

        composeTestRule.setContent {
            DashboardScreen(viewModel = viewModel, onThreadSelected = {}, onNavigateToTab = {})
        }

        // Verify both titles exist initially
        composeTestRule.onNodeWithText("Match This Title").assertExists()
        composeTestRule.onNodeWithText("Ignore This One").assertExists()

        // Set search query
        viewModel.setSearchQuery("Match")

        // Verify only Match This Title is visible
        composeTestRule.onNodeWithText("Match This Title").assertExists()
        composeTestRule.onNodeWithText("Ignore This One").assertDoesNotExist()
    }

    @Test
    fun dashboardScreen_filtersThreadsByStatusActiveArchived() {
        val fixedUserId = "00000000-0000-0000-0000-000000000000"
        val now = java.time.Instant.now().toString()

        val char = CharacterEntity(
            id = "char-1", user_id = fixedUserId, name = "Vex", story = "", core_persona = "", greeting = "",
            appearance = "", style_rules = "", definition = "", negative_guidance = "",
            temperature = 0.7, top_p = 0.9, starters = emptyList(), example_conversations = emptyList(),
            portrait_status = "none", portrait_path = null, portrait_prompt = null,
            portrait_seed = null, portrait_source_hash = null, portrait_last_error = null,
            portrait_generated_at = null, created_at = now, updated_at = now
        )
        val activeThread = ThreadEntity(
            id = "thread-1", user_id = fixedUserId, character_id = "char-1", connection_id = "conn-1",
            model_id = "gemini-1.5-flash", persona_id = null, brain_connection_id = null, brain_model_id = null,
            max_output_tokens = 4096, title = "Active Thread", is_title_autogenerated = false,
            status = "active", archived_at = null, pinned_at = null, created_at = now, updated_at = now
        )
        val archivedThread = ThreadEntity(
            id = "thread-2", user_id = fixedUserId, character_id = "char-1", connection_id = "conn-1",
            model_id = "gemini-1.5-flash", persona_id = null, brain_connection_id = null, brain_model_id = null,
            max_output_tokens = 4096, title = "Archived Thread", is_title_autogenerated = false,
            status = "archived", archived_at = now, pinned_at = null, created_at = now, updated_at = now
        )

        runBlocking {
            db.profileDao().insertProfile(ProfileEntity(fixedUserId, "LocalUser", now, now))
            db.connectionDao().insertConnection(testConnection(fixedUserId, now))
            db.characterDao().insertCharacter(char)
            db.chatDao().insertThread(activeThread)
            db.chatDao().insertThread(archivedThread)
        }

        composeTestRule.setContent {
            DashboardScreen(viewModel = viewModel, onThreadSelected = {}, onNavigateToTab = {})
        }

        // Active thread should be shown, archived thread should not
        composeTestRule.onNodeWithText("Active Thread").assertExists()
        composeTestRule.onNodeWithText("Archived Thread").assertDoesNotExist()

        // Switch to archived filter
        viewModel.setStatusFilter("archived")

        // Archived thread should be shown, active thread should not
        composeTestRule.onNodeWithText("Archived Thread").assertExists()
        composeTestRule.onNodeWithText("Active Thread").assertDoesNotExist()
    }

    private fun testConnection(userId: String, now: String) = ConnectionEntity(
        id = "conn-1",
        user_id = userId,
        provider = "google",
        label = "Google AI",
        base_url = null,
        encrypted_api_key = "key",
        enabled = true,
        default_model_id = "gemini-1.5-flash",
        model_cache = emptyList(),
        health_status = "healthy",
        health_message = "",
        last_checked_at = null,
        last_model_refresh_at = null,
        last_synced_at = null,
        created_at = now,
        updated_at = now
    )
}
