package com.example.open_fantasia.ui.chat

import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.room.Room
import androidx.test.platform.app.InstrumentationRegistry
import com.example.open_fantasia.data.local.db.OpenFantasiaDatabase
import com.example.open_fantasia.data.local.entity.*
import com.example.open_fantasia.data.remote.LLMClient
import com.example.open_fantasia.domain.model.*
import com.example.open_fantasia.domain.usecase.RunContinuityExtractionUseCase
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.emptyFlow
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import java.io.IOException

class ChatScreenTest {

    @get:Rule
    val composeTestRule = createComposeRule()

    private lateinit var db: OpenFantasiaDatabase
    private lateinit var viewModel: ChatViewModel

    private val fakeLlmClient = object : LLMClient {
        override suspend fun discoverModels(connection: ConnectionRecord): List<ModelCatalogEntry> = emptyList()
        override suspend fun generateText(
            connection: ConnectionRecord,
            modelId: String,
            systemPrompt: String,
            messages: List<com.example.open_fantasia.data.remote.ChatMessage>,
            temperature: Double,
            topP: Double,
            maxTokens: Int,
            jsonMode: Boolean
        ): String = "Generated response"

        override fun streamGenerateText(
            connection: ConnectionRecord,
            modelId: String,
            systemPrompt: String,
            messages: List<com.example.open_fantasia.data.remote.ChatMessage>,
            temperature: Double,
            topP: Double,
            maxTokens: Int,
            jsonMode: Boolean
        ): Flow<com.example.open_fantasia.data.remote.StreamChunk> = emptyFlow()
    }

    private val useCase by lazy { RunContinuityExtractionUseCase(fakeLlmClient) }

    @Before
    fun setup() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        db = Room.inMemoryDatabaseBuilder(context, OpenFantasiaDatabase::class.java)
            .allowMainThreadQueries()
            .build()

        val fixedUserId = "00000000-0000-0000-0000-000000000000"
        val now = java.time.Instant.now().toString()

        val char = CharacterEntity(
            id = "char-1",
            user_id = fixedUserId,
            name = "Valeria",
            story = "Obsidian Hall Alliance",
            core_persona = "High Inquisitor",
            greeting = "Who goes there?",
            appearance = "Dark robes",
            style_rules = "Sovereign",
            definition = "",
            negative_guidance = "",
            temperature = 0.7,
            top_p = 0.9,
            starters = emptyList(),
            example_conversations = emptyList(),
            portrait_status = "ready",
            portrait_path = null,
            portrait_prompt = null,
            portrait_seed = null,
            portrait_source_hash = null,
            portrait_last_error = null,
            portrait_generated_at = null,
            created_at = now,
            updated_at = now
        )

        val conn = ConnectionEntity(
            id = "conn-1",
            user_id = fixedUserId,
            provider = "google",
            label = "Google API",
            base_url = null,
            encrypted_api_key = "mock",
            enabled = true,
            default_model_id = "gemini-1.5-flash",
            model_cache = emptyList(),
            health_status = "healthy",
            health_message = "",
            last_checked_at = null,
            last_model_refresh_at = null,
            last_synced_at = null,
            created_at = now,
            updated_at = now
        )

        val thread = ThreadEntity(
            id = "thread-1",
            user_id = fixedUserId,
            character_id = "char-1",
            connection_id = "conn-1",
            model_id = "gemini-1.5-flash",
            persona_id = null,
            brain_connection_id = null,
            brain_model_id = null,
            max_output_tokens = 4096,
            title = "The Obsidian Alliance",
            is_title_autogenerated = false,
            status = "active",
            archived_at = null,
            pinned_at = null,
            created_at = now,
            updated_at = now
        )

        val branch = BranchEntity(
            id = "branch-1",
            thread_id = "thread-1",
            name = "Main Branch",
            parent_branch_id = null,
            fork_turn_id = null,
            head_turn_id = null,
            is_active = true,
            generation_locked = false,
            locked_by_turn_id = null,
            locked_at = null,
            created_by = fixedUserId,
            created_at = now,
            updated_at = now
        )

        runBlocking {
            db.profileDao().insertProfile(ProfileEntity(fixedUserId, "LocalUser", now, now))
            db.characterDao().insertCharacter(char)
            db.connectionDao().insertConnection(conn)
            db.chatDao().insertThread(thread)
            db.chatDao().insertBranch(branch)
        }

        viewModel = ChatViewModel(
            threadId = "thread-1",
            chatDao = db.chatDao(),
            characterDao = db.characterDao(),
            connectionDao = db.connectionDao(),
            personaDao = db.personaDao(),
            llmClient = fakeLlmClient,
            runContinuityExtractionUseCase = useCase
        )
    }

    @After
    @Throws(IOException::class)
    fun tearDown() {
        db.close()
    }

    @Test
    fun chatScreen_showsWorkspace_andDeepScanButton() {
        composeTestRule.setContent {
            ChatScreen(viewModel = viewModel, onBack = {})
        }

        // Verify top bar details
        composeTestRule.onNodeWithText("The Obsidian Alliance").assertExists()
        composeTestRule.onNodeWithText("Branch: Main Branch").assertExists()

        // Open Inspector panel
        composeTestRule.onNodeWithContentDescription("Inspector").performClick()
        
        // Check for cognitive state inspector headers/texts
        composeTestRule.onNodeWithText("Cognitive State Inspector").assertExists()
        composeTestRule.onNodeWithText("No world state materialized yet.").assertExists()
    }
}
